### ISSUE TITLE
Серверная верификация аутентичности пользователя

### ISSUE THREAD

**Issue by bitwheeze** [golos-blockchain/ui-auth#16]
Сейчас можно только в браузере проверить, аутентифицирован ли пользователь или нет. Что бы уменьшить нагрузку на блокчейн и позволить SSR, хочется иметь возможность проверить на сервере, аутентифицирован ли пользователь.  Сейчас же приходится отправлять все через блокчейн, что бы не делать свою дополнительную аутентификацию. 

Возможно я просто не разобрался до конца, но пока не нашел возможности проверить на стороне сервера аутентичность пользователя используя данный сервис. Может просто подскажете.

Я хочу предложить следующее. На данный момент после аутентификации waitForLogin возвращает три атрибута  - account, allowed и authorized. Мне кажется лучше было бы перейти на подписанный сервисом JWT токен.  Что бы waitForLogin возвращал JWT. Тогда клиентская часть приложения могла бы сохранить токен в куках и передавать серверной части токен в запросах. А серверная часть могла бы обратившись к oAuth сервису проверить токен. Не обязательно с каждым запросом, я думаю достаточно один раз. Время жизни токена указанно же в самом токене.

**Comment by 1aerostorm** [comment]
@bitwheeze скорее следует не перейти, а добавить подобный токен в дополнение к имеющемуся функционал.

Ведь "перейти" подразумевает, что этот токен будет использоваться и для отправки операций. А давать возможность серверам приложений отправлять операции - очень нежелательно с точки зрения безопасности. Пользователь закрывает браузер, уезжает в тайгу на месяц, а сервер все это время может отправлять какие-то операции без его ведома, пока не истечет срок у токена... Ну такое.

Хочется, чтобы токен позволял только проверять, авторизован ли пользователь в OAuth, то есть работал как waitForLogin, но не более.

Подойдет ли такой вариант? Если нет, объясни как можно подробнее, зачем так уж нужно отправлять операции с сервера и какие.

**Comment by bitwheeze** [comment]
> Поэтому хочется, чтобы токен позволял только проверять, авторизован ли пользователь в OAuth

Я только это и имел ввиду. Нужно только проверить на сервере, авторизирован ли пользователь (account) или нет.

Сейчас пользователь авторизировн только в браузере, api бэкэенда игрушки пока никак не защищено. Единственная возможность проверить аутентичность действий пользователя в игре, отправить эти действия через блокчейн и бэкэндом ловить их в блоках.  Потому сейчас все ходы в игре отправляются через блокчейн, через OAuth сервер. Это во первых лишняя нагрузка на OAuth сервер, во вторых ответа приходится ждать долго. 3-6 секунд.

Потому Что бы снять нагрузку на oAuth и заодно ускорить ответную реакцию бэкенда, надо как то защитить API, или иначе говоря позволить менять игровое состояние на бэкенде только авторизированому пользователю. Вот для этого и нужна возможность проверить на стороне бэкенда авторизацию пользователя. 

Отправлять транзакции на стороне бэкенда через oAuth наверное тоже интересно для каких нибудь ботов, но лично мне пока этого не требуется. Оно и сейчас не нужно. Бэкенд у меня ничего от имени пользователя не делает. 

Под "перейти", я понимал только заменить ответ от waitForLogin на JWT токен или какой то хэш, который можно отправлять куками бэкенду, что бы тот мог делать запросы к oAuth, что бы проверить валидность токена. Сейчас это просто кастомная стурктура, часть параметров которой просто не используется.

**Comment by Lex-Ai** [comment]
Обновление ушло, протестируй

https://github.com/golos-blockchain/ui-auth/blob/master/API.md#%D1%81%D0%B5%D1%80%D0%B2%D0%B5%D1%80%D0%BD%D1%8B%D0%B9-%D1%82%D0%BE%D0%BA%D0%B5%D0%BD-%D0%B0%D0%B2%D1%82%D0%BE%D1%80%D0%B8%D0%B7%D0%B0%D1%86%D0%B8%D0%B8
